# Info that changes with each new release
# (get sha256 from https://pypi.org/project/imageio/#files)

{% set version = "2.4.0" %}
{% set sha256 = "fed45addbbd95a22739a607a9cfbd0ebcf641d4f42edb877f76957df322b50f8" %}

package:
  name: imageio
  version: {{ version }}

source:
  fn: imageio-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/imageio/imageio-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy
    - pillow

test:
  imports:
    - imageio

about:
  home: http://imageio.github.io
  doc_url: http://imageio.readthedocs.io
  dev_url: https://github.com/imageio/imageio
  summary: a Python library for reading and writing image data
  license: BSD 2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - almarklein
    - blink1073
    - jni
